/** Stable public URLs — copied from `public/images/` at build time (works on Vercel & local). */
export const siteImages = {
  logo: "/images/pakman-logo.jpeg",
  hero: "/images/hero-arrangement.jpg",
  about: "/images/about-arrangement.jpg",
  saudiMap: "/images/saudi-map.jpg",
  clients: {
    subbie: "/images/clients/subbie.jpeg",
    btc: "/images/clients/btc.jpeg",
    tastingSpoon: "/images/clients/tasting-spoon.jpeg",
    evolve: "/images/clients/evolve.jpeg",
    prepd: "/images/clients/prepd.jpeg",
    fornia: "/images/clients/fornia.jpeg",
    circleSection: "/images/clients/circle-section.jpeg",
  },
  cat: {
    coffeeCups: "/images/cat/coffee-cups.jpg",
    coldCups: "/images/cat/cold-cups.jpg",
    clearCups: "/images/cat/clear-cups.jpg",
    cupLids: "/images/cat/cup-lids.jpg",
    cupSleeves: "/images/cat/cup-sleeves.jpg",
    paperBags: "/images/cat/paper-bags.jpg",
    burgerBoxes: "/images/cat/burger-boxes.jpg",
    sandwichBoxes: "/images/cat/sandwich-boxes.jpg",
    foodContainers: "/images/cat/food-containers.jpg",
    saladBowls: "/images/cat/salad-bowls.jpg",
    soupBowls: "/images/cat/soup-bowls.jpg",
    plates: "/images/cat/plates.jpg",
    pizzaBoxes: "/images/cat/pizza-boxes.jpg",
    bakeryBoxes: "/images/cat/bakery-boxes.jpg",
    napkins: "/images/cat/napkins.jpg",
    cutlery: "/images/cat/cutlery.jpg",
    labels: "/images/cat/labels.jpg",
    stickers: "/images/cat/stickers.jpg",
    wrappingPaper: "/images/cat/wrapping-paper.jpg",
    takeaway: "/images/cat/takeaway.jpg",
    delivery: "/images/cat/delivery.jpg",
    tissueBoxes: "/images/cat/tissue-boxes.jpg",
    customPrinted: "/images/cat/custom-printed.jpg",
  },
} as const;

export const categoryImages = [
  siteImages.cat.coffeeCups,
  siteImages.cat.coldCups,
  siteImages.cat.clearCups,
  siteImages.cat.cupLids,
  siteImages.cat.cupSleeves,
  siteImages.cat.paperBags,
  siteImages.cat.burgerBoxes,
  siteImages.cat.sandwichBoxes,
  siteImages.cat.foodContainers,
  siteImages.cat.saladBowls,
  siteImages.cat.soupBowls,
  siteImages.cat.plates,
  siteImages.cat.pizzaBoxes,
  siteImages.cat.bakeryBoxes,
  siteImages.cat.napkins,
  siteImages.cat.cutlery,
  siteImages.cat.labels,
  siteImages.cat.stickers,
  siteImages.cat.wrappingPaper,
  siteImages.cat.takeaway,
  siteImages.cat.delivery,
  siteImages.cat.tissueBoxes,
  siteImages.cat.customPrinted,
];
